### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by MrCrazyLeo** [ikcamp/Efficient-Mobile-Web-FE-Development#3]
[勘误.pdf](https://github.com/ikcamp/Efficient-Mobile-Web-FE-Development/files/3818560/default.pdf)
你好，IKcamp团队，我最近在拜读你们的前端的书《移动web前端高效开发实战》，发现书中几处明显出错的地方。由于知识尚浅，有些代码是我仅凭目前浅薄的知识改的，如若不妥可以不理。

**Comment by MrCrazyLeo** [comment]
后边我还没看完，现在手头有几个新的出错的地方，不定时再更新。希望作者团队有空看下，谢谢~

**Comment by zhouyao** [comment]
感谢~
